#!/bin/sh


# some administrative
PRINTF="/usr/bin/printf"
DATE="/usr/bin/date"
EDITOR=${EDITOR:-vim}

AGENDA_D="$HOME/doc/school/agenda"
AGENDA_T="$HOME/doc/school/agenda.template"

DATE_STR="now"

# User may optionally specify a date offset in
# days as the first argument.
if [ -n "$1" ]; then
	DATE_STR="$DATE_STR $1 day"
fi

datetarget() {
	$DATE --date="$DATE_STR" "$@"
}

# variables the agenda template can substitute
# when creating new agendas.
export TARGET=$(datetarget +'%Y-%m-%d')
export TARGET_NICE=$(datetarget +'%A, %B %e, %Y')

AGENDA="$AGENDA_D/$TARGET.md"

# make sure the agenda directory exists
[ ! -d "$AGENDA_D" ] && mkdir -p "$AGENDA_D"

# make sure the agenda template exists. If not,
# echo a simple date into it as the template.
[ ! -f "$AGENDA_T" ] && $PRINTF '${TARGET_NICE}\n\n\n' > "$AGENDA_T"

# create a new agenda if one does not exist for
# today, otherwise open the existing one.
if [ ! -e "$AGENDA" ]; then
	envsubst < "$AGENDA_T" > "$AGENDA"
fi

$EDITOR "$AGENDA"
